lis_size = size(cubic_lis);
cubic_num = lis_size(1);
for i=1:cubic_num
    cubic = cubic_lis(i, :);
    node = cubic(1);
    node1 = [node.x, node.y, node.z];
    node = cubic(2);
    node2 = [node.x, node.y, node.z];
    node = cubic(3);
    node3 = [node.x, node.y, node.z];
    node = cubic(4);
    node4 = [node.x, node.y, node.z];
    node = cubic(5);
    node5 = [node.x, node.y, node.z];
    node = cubic(6);
    node6 = [node.x, node.y, node.z];
    node = cubic(7);
    node7 = [node.x, node.y, node.z];
    node = cubic(8);
    node8 = [node.x, node.y, node.z];
    line = [node1;node2];
    plot3(line(:, 1), line(:, 2), line(:, 3), Color=color);
    hold on;
    line = [node2;node3];
    plot3(line(:, 1), line(:, 2), line(:, 3), Color=color);
    hold on;
    line = [node3;node4];
    plot3(line(:, 1), line(:, 2), line(:, 3), Color=color);
    hold on;
    line = [node4;node1];
    plot3(line(:, 1), line(:, 2), line(:, 3), Color=color);
    hold on;
    line = [node5;node8];
    plot3(line(:, 1), line(:, 2), line(:, 3), Color=color);
    hold on;
    line = [node5;node6];
    plot3(line(:, 1), line(:, 2), line(:, 3), Color=color);
    hold on;
    line = [node6;node7];
    plot3(line(:, 1), line(:, 2), line(:, 3), Color=color);
    hold on;
    line = [node7;node8];
    plot3(line(:, 1), line(:, 2), line(:, 3), Color=color);
    hold on;
    line = [node1;node5];
    plot3(line(:, 1), line(:, 2), line(:, 3), Color=color);
    hold on;
    line = [node2;node6];
    plot3(line(:, 1), line(:, 2), line(:, 3), Color=color);
    hold on;
    line = [node3;node7];
    plot3(line(:, 1), line(:, 2), line(:, 3), Color=color);
    hold on;
    line = [node4;node8];
    plot3(line(:, 1), line(:, 2), line(:, 3), Color=color);
    hold on;
    xlabel("X axis");
    ylabel("Y axis");
    zlabel("Z axis");
end